projects:
  - name: Production
    environments:
        - name: Production
          services:
            - type: web
              plan: free
              name: friend-finder-backend
              runtime: python
              repo: https://github.com/SkryptyUJ/friend-finder
              branch: main
              autoDeployTrigger: commit
              buildCommand: pip install -r backend/requirements.txt
              startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT backend.main:app
              healthCheckPath: /health
              envVars:
                - key: PYTHON_VERSION
                  value: 3.14.0